# Generated by Django 5.2.13 on 2026-04-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0003_alter_importjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importissue',
            name='severity',
            field=models.CharField(choices=[('FATAL', 'Fatal'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10),
        ),
        migrations.CreateModel(
            name='ImportRowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=120)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('entity', models.CharField(blank=True, max_length=120)),
                ('record_identifier', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('SKIPPED', 'Omitido'), ('ERROR', 'Error'), ('WARNING', 'Advertencia')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('fields_affected', models.JSONField(blank=True, default=list)),
                ('issue_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='data_imports.importjob')),
                ('sheet_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_results', to='data_imports.importsheetresult')),
            ],
            options={
                'ordering': ['sheet_name', 'row_number', 'created_at'],
                'indexes': [models.Index(fields=['import_job', 'action'], name='data_import_import__7fbdef_idx'), models.Index(fields=['sheet_name', 'row_number'], name='data_import_sheet_n_3ebeb7_idx')],
            },
        ),
    ]
