# Generated by Django 6.0.4 on 2026-07-27 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_alter_parcel_codigo_parcela_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('geometry_type', models.CharField(choices=[('POINT', 'Punto'), ('LINE', 'Linea'), ('POLYGON', 'Poligono'), ('ANY', 'Cualquiera')], db_index=True, default='ANY', max_length=20)),
                ('color', models.CharField(default='#2563eb', max_length=9)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('extra_schema', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria georreferenciada',
                'verbose_name_plural': 'Categorias georreferenciadas',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('geometry_type', models.CharField(choices=[('POINT', 'Punto'), ('LINE', 'Linea'), ('POLYGON', 'Poligono'), ('ANY', 'Cualquiera')], db_index=True, max_length=20)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('operational_status', models.CharField(choices=[('ACTIVE', 'Operativo'), ('MAINTENANCE', 'En mantencion'), ('REVIEW', 'Requiere revision'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('UNKNOWN', 'Sin estado')], db_index=True, default='ACTIVE', max_length=20)),
                ('criticality', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Critica')], db_index=True, default='MEDIUM', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('min_lng', models.FloatField(blank=True, db_index=True, null=True)),
                ('min_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('max_lng', models.FloatField(blank=True, db_index=True, null=True)),
                ('max_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(default=0)),
                ('perimeter_m', models.FloatField(default=0)),
                ('area_m2', models.FloatField(default=0)),
                ('vertex_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_assets', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='geo_operations.geoassetcategory')),
            ],
            options={
                'verbose_name': 'Elemento georreferenciado',
                'verbose_name_plural': 'Elementos georreferenciados',
                'ordering': ['category__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeoAssetChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='geo_operations.geoasset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_asset_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de elemento georreferenciado',
                'verbose_name_plural': 'Cambios de elementos georreferenciados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geoasset',
            index=models.Index(fields=['is_deleted', 'is_active', 'category'], name='geo_operati_is_dele_b2b10c_idx'),
        ),
        migrations.AddIndex(
            model_name='geoasset',
            index=models.Index(fields=['geometry_type', 'operational_status', 'criticality'], name='geo_operati_geometr_8f0b78_idx'),
        ),
        migrations.AddIndex(
            model_name='geoasset',
            index=models.Index(fields=['min_lng', 'min_lat', 'max_lng', 'max_lat'], name='geo_operati_min_lng_0e9117_idx'),
        ),
    ]
