# Generated by Django 6.0.4 on 2026-07-27 23:54

import apps.geo_operations.models
from django.db import migrations, models


INITIAL_SERVICE_TYPES = {
    'canales-agua': 'WATER',
    'grifos-incendio': 'SECURITY',
    'luminarias-caminos': 'ELECTRIC',
    'pozos': 'WATER',
    'camaras-seguridad': 'SECURITY',
    'lineas-electricas': 'ELECTRIC',
    'tuberias': 'WATER',
    'valvulas': 'WATER',
    'estanques': 'WATER',
    'bombas': 'WATER',
    'caminos': 'ROADS',
    'cercos': 'SECURITY',
    'portones': 'SECURITY',
    'postes': 'ELECTRIC',
    'alcantarillas': 'ROADS',
    'puntos-criticos': 'RISK',
    'zonas-riesgo': 'RISK',
    'areas-verdes': 'GREEN_AREAS',
    'puntos-con-foto': 'INSPECTION',
    'instalaciones-generales': 'GENERAL',
}


def classify_categories(apps, schema_editor):
    GeoAssetCategory = apps.get_model('geo_operations', 'GeoAssetCategory')
    for slug, service_type in INITIAL_SERVICE_TYPES.items():
        GeoAssetCategory.objects.filter(slug=slug).update(service_type=service_type)
    GeoAssetCategory.objects.update_or_create(
        slug='puntos-con-foto',
        defaults={
            'name': 'Puntos con foto',
            'description': 'Registros fotograficos levantados en terreno con ubicacion GPS.',
            'service_type': 'INSPECTION',
            'geometry_type': 'POINT',
            'color': '#7c3aed',
            'icon': 'camera',
            'sort_order': 185,
            'is_active': True,
            'extra_schema': {},
            'is_deleted': False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('geo_operations', '0002_seed_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoasset',
            name='photo',
            field=models.FileField(blank=True, upload_to=apps.geo_operations.models.geo_asset_photo_upload_to),
        ),
        migrations.AddField(
            model_name='geoasset',
            name='photo_content_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='geoasset',
            name='photo_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoasset',
            name='photo_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='geoasset',
            name='photo_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoasset',
            name='photo_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geoassetcategory',
            name='service_type',
            field=models.CharField(choices=[('ELECTRIC', 'Servicio electrico'), ('WATER', 'Servicio de aguas'), ('SECURITY', 'Seguridad'), ('ROADS', 'Vialidad'), ('GREEN_AREAS', 'Areas verdes'), ('RISK', 'Riesgos'), ('INSPECTION', 'Inspeccion en terreno'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.RunPython(classify_categories, migrations.RunPython.noop),
    ]
