# Generated by Django 6.0.4 on 2026-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rut_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
