# Generated by Django 5.2.13 on 2026-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneflight',
            name='team_code',
            field=models.CharField(blank=True, choices=[('SENTRY_32', 'Sentry 32'), ('SENTRY_33', 'Sentry 33'), ('SENTRY_ZOOM_31', 'Sentry Zoom 31'), ('SENTRY_ENTERPRISE_30', 'Sentry Enterprise 30')], max_length=40),
        ),
    ]
