INITIAL_GEO_CATEGORIES = [
    {
        'name': 'Canales de agua',
        'slug': 'canales-agua',
        'description': 'Trazados y superficies asociadas a canales de agua.',
        'geometry_type': 'ANY',
        'color': '#0ea5e9',
        'icon': 'water',
        'sort_order': 10,
    },
    {
        'name': 'Grifos contra incendios',
        'slug': 'grifos-incendio',
        'description': 'Puntos de abastecimiento para emergencia contra incendios.',
        'geometry_type': 'POINT',
        'color': '#ef4444',
        'icon': 'fire-hydrant',
        'sort_order': 20,
    },
    {
        'name': 'Luminarias de caminos',
        'slug': 'luminarias-caminos',
        'description': 'Luminarias y puntos de alumbrado vial.',
        'geometry_type': 'POINT',
        'color': '#f59e0b',
        'icon': 'lightbulb',
        'sort_order': 30,
    },
    {
        'name': 'Pozos',
        'slug': 'pozos',
        'description': 'Pozos, norias y puntos de captacion.',
        'geometry_type': 'POINT',
        'color': '#2563eb',
        'icon': 'droplet',
        'sort_order': 40,
    },
    {
        'name': 'Camaras de seguridad',
        'slug': 'camaras-seguridad',
        'description': 'Camaras y puntos de observacion operacional.',
        'geometry_type': 'POINT',
        'color': '#7c3aed',
        'icon': 'camera',
        'sort_order': 50,
    },
    {
        'name': 'Lineas electricas',
        'slug': 'lineas-electricas',
        'description': 'Tendidos y trazados electricos.',
        'geometry_type': 'LINE',
        'color': '#eab308',
        'icon': 'bolt',
        'sort_order': 60,
    },
    {
        'name': 'Tuberias',
        'slug': 'tuberias',
        'description': 'Tuberias y redes hidraulicas o sanitarias.',
        'geometry_type': 'LINE',
        'color': '#14b8a6',
        'icon': 'pipe',
        'sort_order': 70,
    },
    {
        'name': 'Valvulas',
        'slug': 'valvulas',
        'description': 'Valvulas de corte o control de redes.',
        'geometry_type': 'POINT',
        'color': '#0891b2',
        'icon': 'valve',
        'sort_order': 80,
    },
    {
        'name': 'Estanques',
        'slug': 'estanques',
        'description': 'Estanques, acumuladores y reservas.',
        'geometry_type': 'POINT',
        'color': '#0284c7',
        'icon': 'tank',
        'sort_order': 90,
    },
    {
        'name': 'Bombas',
        'slug': 'bombas',
        'description': 'Bombas, salas de bomba y equipos asociados.',
        'geometry_type': 'POINT',
        'color': '#0f766e',
        'icon': 'pump',
        'sort_order': 100,
    },
    {
        'name': 'Caminos',
        'slug': 'caminos',
        'description': 'Caminos, huellas y trazados viales.',
        'geometry_type': 'LINE',
        'color': '#64748b',
        'icon': 'road',
        'sort_order': 110,
    },
    {
        'name': 'Cercos',
        'slug': 'cercos',
        'description': 'Cercos, deslindes y cierres perimetrales.',
        'geometry_type': 'LINE',
        'color': '#92400e',
        'icon': 'fence',
        'sort_order': 120,
    },
    {
        'name': 'Portones',
        'slug': 'portones',
        'description': 'Portones fisicos y accesos controlados.',
        'geometry_type': 'POINT',
        'color': '#1d4ed8',
        'icon': 'gate',
        'sort_order': 130,
    },
    {
        'name': 'Postes',
        'slug': 'postes',
        'description': 'Postes electricos, de comunicacion o soporte.',
        'geometry_type': 'POINT',
        'color': '#a16207',
        'icon': 'pole',
        'sort_order': 140,
    },
    {
        'name': 'Alcantarillas',
        'slug': 'alcantarillas',
        'description': 'Alcantarillas, pasos de agua y obras menores.',
        'geometry_type': 'POINT',
        'color': '#475569',
        'icon': 'culvert',
        'sort_order': 150,
    },
    {
        'name': 'Puntos criticos',
        'slug': 'puntos-criticos',
        'description': 'Puntos que requieren observacion o seguimiento especial.',
        'geometry_type': 'POINT',
        'color': '#dc2626',
        'icon': 'alert-triangle',
        'sort_order': 160,
    },
    {
        'name': 'Zonas de riesgo',
        'slug': 'zonas-riesgo',
        'description': 'Areas con riesgo operacional, ambiental o de seguridad.',
        'geometry_type': 'POLYGON',
        'color': '#f97316',
        'icon': 'warning-zone',
        'sort_order': 170,
    },
    {
        'name': 'Areas verdes',
        'slug': 'areas-verdes',
        'description': 'Areas verdes, parques y zonas de mantencion vegetal.',
        'geometry_type': 'POLYGON',
        'color': '#16a34a',
        'icon': 'trees',
        'sort_order': 180,
    },
    {
        'name': 'Instalaciones generales',
        'slug': 'instalaciones-generales',
        'description': 'Infraestructura operacional no clasificada en otras categorias.',
        'geometry_type': 'ANY',
        'color': '#334155',
        'icon': 'landmark',
        'sort_order': 190,
    },
]
